version: '3'
services:
  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_DB: jareth_test
    ports:
      - "5434:5432"
    volumes:
      - "./tmp/db-data:/var/lib/postgresql/data"